openapi: 3.1.0
info:
  title: FastAPI OpenAPI Quickstart
  version: 1.0.0
  description: |
    API specification for a simple Python service providing a health check,
    current time, and greeting endpoint.
servers:
  - url: http://localhost:8000
    description: Local development server
paths:
  /health:
    get:
      summary: Health check
      description: Return service health status.
      operationId: getHealth
      responses:
        '200':
          description: Service is healthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              examples:
                ok:
                  summary: Healthy response
                  value:
                    status: ok
  /time:
    get:
      summary: Current time
      description: Return the current server time in ISO 8601 format (UTC recommended).
      operationId: getCurrentTime
      responses:
        '200':
          description: Current time returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeResponse'
              examples:
                sample:
                  summary: Example current time response
                  value:
                    current_time: '2025-09-12T10:15:30Z'
  /greet:
    post:
      summary: Greet a user by name
      description: Accept a name and return a friendly greeting message.
      operationId: postGreet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GreetRequest'
            examples:
              sample:
                summary: Example greet request
                value:
                  name: Alice
      responses:
        '200':
          description: Greeting message returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GreetResponse'
              examples:
                sample:
                  summary: Example greet response
                  value:
                    message: 'hello Alice!'
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                missingName:
                  summary: Missing name
                  value:
                    error: 'name is required'
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Health status string, typically "ok".
          example: ok
      required:
        - status
    TimeResponse:
      type: object
      properties:
        current_time:
          type: string
          format: date-time
          description: Current server time in ISO 8601 format.
          example: '2025-09-12T10:15:30Z'
      required:
        - current_time
    GreetRequest:
      type: object
      properties:
        name:
          type: string
          description: Name to greet.
          minLength: 1
          example: Alice
      required:
        - name
    GreetResponse:
      type: object
      properties:
        message:
          type: string
          description: Greeting message including the provided name.
          example: 'hello Alice!'
      required:
        - message
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message.
          example: 'name is required'
      required:
        - error
